name: verify manifests
on:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          for manifest in *.json; do
            jq < "$manifest" >/dev/null
          done
